# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fitDPSPN <- function(data, D1, Dp, clstrAssign = as.integer( c(-1)), nSamp = 50L, nBurn = 900L, nThin = 2L, updateAlpha = 0L, displayProgress = 1L) {
    .Call(`_DPSPN_fitDPSPN`, data, D1, Dp, clstrAssign, nSamp, nBurn, nThin, updateAlpha, displayProgress)
}

fitHDPSPN <- function(data, rid, D1, Dp, clstrAssign = as.integer( c(-1)), nSamp = 50L, nBurn = 900L, nThin = 2L, updateAlpha = 0L, displayProgress = 1L) {
    .Call(`_DPSPN_fitHDPSPN`, data, rid, D1, Dp, clstrAssign, nSamp, nBurn, nThin, updateAlpha, displayProgress)
}

computeLoglikhd <- function(data, Dcir, param) {
    .Call(`_DPSPN_computeLoglikhd`, data, Dcir, param)
}

